---
title: "Run EucsPhylogenomics"
---

```{r setup, include=FALSE}
# create output directories
outdir_clean_reads <- file.path(currentdir, "01_clean_reads")
outdir_assemblies <- file.path(currentdir, "02_assemblies")
outdir_extractions <- file.path(currentdir, "03_extractions")
outdir_extractions_all <- file.path(outdir_extractions, "all/")
outdir_alignments <- file.path(currentdir, "04_alignments")
outdir_final <- file.path(currentdir, "05_final")
sapply(c(outdir_clean_reads, outdir_assemblies, outdir_extractions, outdir_extractions_all, outdir_alignments, outdir_final), function(x) {
  if (!dir.exists(x)) { dir.create(x, recursive=T) }})

# open CAPTUS metadata
df_captus_sample_metadata <- data.table::fread(params$fn_captus_sample_metadata)
df_captus_target_metadata <- data.table::fread(params$fn_captus_target_metadata)
ls_group <- unique(df_captus_target_metadata$group)
```

```{r run-captus}
# run CAPTUS to clean raw reads
f_run_captus_cleaning(params$exe_captus, params$dir_fastq, outdir_clean_reads, params$thread, params$redo) 

# extract all cleaned FASTQ files
all_fastq <- list.files(outdir_clean_reads, full.names=FALSE)

# run CAPTUS assemble and extraction for each group
for (group in ls_group) {
    # update group name
    group_no_ws <- gsub("\\s+", "", group)

    # output directory
    outdir_clean_reads_group <- file.path(outdir_clean_reads, group_no_ws)
    outdir_assemblies_group <- file.path(outdir_assemblies, group_no_ws)
    outdir_extractions_group <- file.path(outdir_extractions, group_no_ws)
    sapply(c(outdir_clean_reads_group, outdir_assemblies_group, outdir_extractions_group), function(x) {
        if (!dir.exists(x)) { dir.create(x, recursive=T) }})

    # move the CAPTUS output directories
    ls_group_sample <- df_captus_sample_metadata$sample[df_captus_sample_metadata$group==group]
    for (sample in ls_group_sample) {
        # extract file pattern
        pattern <- str_c(str_escape(sample), "(?![A-Za-z0-9])")
        ls_match <- all_fastq[str_starts(all_fastq, pattern)]

        if (length(ls_match) > 0) {
            file.rename(file.path(outdir_clean_reads, ls_match),
                        file.path(outdir_clean_reads_group, ls_match))
        }
    }

    # run CAPTUS assemble
    f_run_captus_assembly(params$exe_captus, outdir_clean_reads_group, outdir_assemblies_group, params$thread, params$redo)

    # run CAPTUS extraction
    f_run_captus_extraction(params$exe_captus,
                            df_captus_target_metadata$dir_target_loci[df_captus_target_metadata$group==group], 
                            outdir_assemblies_group,
                            outdir_extractions_group,
                            params$thread,
                            params$redo)

    # move all CAPTUS extractions to one folder
    system(paste("mv",
                 paste0(outdir_extractions_group, "/*captus-ext"),
                 outdir_extractions_all))
}

# check if previous results are provided
if (params$dir_locus_alignment!="" && dir.exists(params$dir_locus_alignment)) {
    # create doSNOW clusters
    nwcl <- makeCluster(params$thread)
    registerDoSNOW(nwcl)

    # output directory
    outdir_alignments_sequence <- file.path(outdir_alignments, "01_sequence")
    outdir_alignments_mafftadd <- file.path(outdir_alignments, "02_mafftadd")
    sapply(c(outdir_alignments_sequence, outdir_alignments_mafftadd), function(x) {
        if (!dir.exists(x)) { dir.create(x, recursive=T) }})

    # extract list of samples
    ls_sample <- list.dirs(outdir_extractions_all, recursive=F, full.names=F)
    ls_sample <- gsub("__captus-ext", "", ls_sample)

    # iterate over samples
    for (sample in ls_sample) {
        # open matched DNA sequences
        seqs <- Biostrings::readBStringSet(file.path(outdir_extractions_all, paste0(sample, "__captus-ext"), "04_misc_DNA", "DNA_matches.fna"))

        # only keep the best hits for each locus
        best_hits <- seqs[grepl("\\[hit=00\\]", names(seqs))]

        # extract the list of locus
        ls_locus <- sapply(names(best_hits), function(x) {
            locus <- unlist(strsplit(x, split="__"))[2]
            locus <- unlist(strsplit(locus, split=" "))[1]
            locus
        })

        # iterate over loci
        foreach (locus=unique(ls_locus), .packages="Biostrings") %dopar% {
            # output file
            fn_locus_seqs <- file.path(outdir_alignments_sequence, paste0(locus, ".fna"))

            # extract locus sequence
            locus_seq <- best_hits[ls_locus==locus]
            if (length(locus_seq)!=1) {
                log4r::warn(fn_logger, paste0("Multiple sequences of ", locus, " for ", sample, "."))
            }

            writeXStringSet(locus_seq, filepath=fn_locus_seqs, append=T)
        }
    }

    # add BUSCO sequences to existing alignment
    ls_ref_locus <- list.files(params$dir_locus_alignment, recursive=F, full.names=T)
    
    # iterate over loci
    foreach (locus_path = ls_ref_locus) %dopar% {
        # extract locus name
        locus <- tools::file_path_sans_ext(basename(locus_path))

        # input file
        fn_locus_seqs <- file.path(outdir_alignments_sequence, paste0(locus, ".fna"))
        
        # output file
        fn_alignments_locus <- file.path(outdir_alignments_mafftadd, paste0(locus, ".fna"))

        # run MAFFT --add
        if (file.exists(fn_locus_seqs)) {
            f_mafft_add(locus_path, fn_locus_seqs, fn_alignments_locus, params$exe_mafft)
        } else {
            system(paste("cp", locus_path, fn_alignments_locus))
            log4r::warn(fn_logger, paste0("No additional sequences for ", locus, "."))
        }
    }

    stopCluster(nwcl)

} else {
    # run CAPTUS align
    f_run_captus_alignment(params$exe_captus, outdir_extractions_all, outdir_alignments, params$thread, params$redo)
}
```

```{r filter-alignment}
# create output directories
outdir_final_seq50 <- file.path(outdir_final, "01_seq50")
outdir_final_col50 <- file.path(outdir_final, "02_col50")
outdir_final_trimlabel <- file.path(outdir_final, "03_trimlabel")
outdir_final_genetrees <- file.path(outdir_final, "04_genetrees")
outdir_final_treeshrink <- file.path(outdir_final, "05_treeshrink")
outdir_locus_alignment <- file.path(outdir_final_treeshrink, "alignments")
outdir_locus_tree <- file.path(outdir_final_treeshrink, "trees")
sapply(c(outdir_final_seq50, outdir_final_col50, outdir_final_trimlabel, outdir_final_genetrees, outdir_locus_alignment, outdir_locus_tree), function(x) {
  if (!dir.exists(x)) { dir.create(x, recursive=T) }})

# output files
fn_captus_summary <- file.path(currentdir, "captus_summary.tsv")
fn_concatenated <- file.path(outdir_final_treeshrink, "concatenated.out")
fn_partition <- file.path(outdir_final_treeshrink, "partitions.nex")
fn_partition_model <- file.path(outdir_final_treeshrink, "partitions_with_models.nex")
fn_concatenated_filtered <- file.path(outdir_final_treeshrink, "concatenated.fna")

# extract list of locus
ls_locus <- c()
if (dir.exists(params$dir_locus_alignment)) {
    ls_locus <- list.files(file.path(outdir_alignments, "02_mafftadd"), recursive=F, full.names=F)
} else {
    ls_locus <- list.files(file.path(outdir_alignments, "03_trimmed", "05_naive", "04_misc_DNA", "01_matches"), recursive=F, full.names=F)
}   
ls_locus <- gsub("\\.fna", "", ls_locus)

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# iterate over locus
if (!file.exists(fn_captus_summary) || params$redo) {
    df_captus_label <- foreach (locus=ls_locus, .combine='rbind') %dopar% {
        require(data.table)

        # input files
        fn_input <- file.path(outdir_alignments, "03_trimmed", "05_naive", "04_misc_DNA", "01_matches", paste0(locus, ".fna"))
        if (dir.exists(params$dir_locus_alignment)) {
            fn_input <- file.path(outdir_alignments, "02_mafftadd", paste0(locus, ".fna"))
        }

        fn_seq50 <- file.path(outdir_final_seq50, paste0(locus, ".fna"))
        fn_col50 <- file.path(outdir_final_col50, paste0(locus, ".fna"))
        fn_trimlabel <- file.path(outdir_final_trimlabel, paste0(locus, ".fna"))

        # filter locus alignment
        f_remove_seq(fn_input, fn_seq50, 0.5)
        f_remove_col(fn_seq50, fn_col50, 0.5)
        df_captus_label_locus <- f_trim_captus_label(fn_col50, locus, fn_trimlabel)

        return(df_captus_label_locus)
    }

    data.table::fwrite(df_captus_label, file=fn_captus_summary, sep="\t", quote=F)
}

# iterate over loci
foreach (locus = ls_locus) %dopar% {
    # input file
    fn_input <- file.path(outdir_final_trimlabel, paste0(locus, ".fna"))

    # output files
    prefix <- paste0(outdir_final_genetrees, "/", locus)
    fn_iqtree_tre <- file.path(outdir_final_genetrees, paste0(locus, ".treefile"))
    fn_treeshrink_tre <- file.path(outdir_locus_tree, paste0(locus, ".treefile"))
    fn_treeshrink_aln <- file.path(outdir_locus_alignment, paste0(locus, ".fna"))

    # infer gene tree
    f_iqtree2_singlethread(fn_input, prefix, params$redo, params$exe_iqtree)

    # run TreeShrink
    f_treeshrink(fn_iqtree_tre, locus, outdir_locus_tree, params$exe_treeshrink)

    # subset alignments
    f_subset_alignment(fn_treeshrink_tre, fn_input, fn_treeshrink_aln)
}

stopCluster(nwcl)

# concatenate locus alignments
f_amas_dna(input_regex=file.path(outdir_locus_alignment, "*.fna"),
           fn_output_aln=fn_concatenated,
           fn_output_part=fn_partition,
           exe_amas=params$exe_amas)
f_unknown2gap(fn_concatenated, fn_concatenated_filtered)

# extract best models
df_partition <- f_extract_best_models(outdir_final_genetrees, fn_partition)
if (any(is.na(df_partition$model))) {
    log4r::error(fn_logger, "One or more loci have no matched model. Exited.")
    knitr::knit_exit()
}

# write the partitions and models
con <- file(fn_partition_model, "w")
writeLines("#nexus", con)
writeLines("begin sets;", con)

# add charset lines
for (i in seq_len(nrow(df_partition))) {
  writeLines(sprintf("    charset %s = %s;", df_partition$locus[i], df_partition$coords[i]),
             con=con)
}

# add models
ls_partition <- sprintf("%s:%s", df_partition$model, df_partition$locus)
ls_partition <- paste(ls_partition, collapse=", ")
writeLines(sprintf("    charpartition mine = %s;", ls_partition),
           con=con)

writeLines("end;", con)
close(con)
```

```{r tree}
# output files
fn_veryfasttree <- file.path(outdir_final_treeshrink, "veryfasttree.treefile")
fn_concat_tre <- file.path(outdir_final_treeshrink, "concat.treefile")
fn_alltrees_tre <- file.path(outdir_final_treeshrink, "alltrees.tre")
fn_astral_tre <- file.path(outdir_final_treeshrink, "concat_qcf.tre")
fn_astral_log <- file.path(outdir_final_treeshrink, "concat_qcf.log")

# check if previous tree is provided
if (params$fn_species_tree!="" && file.exists(params$fn_species_tree)) {
    # refine the species tree using IQ-TREE2
    f_iqtree2_fixtop(fn_input=fn_concatenated_filtered,
                     fn_tree=params$fn_species_tree,
                     fn_partition=fn_partition_model,
                     prefix=paste0(outdir_final_treeshrink, "/concat"),
                     thread=params$thread,
                     is_redo=params$redo,
                     exe_iqtree2=params$exe_iqtree)

} else {
    # check if file exists
    if (!file.exists(fn_concat_tre) || params$redo) {
        # infer VeryFastTree tree
        f_veryfasttree(fn_fasta=fn_concatenated_filtered,
                       fn_output=fn_veryfasttree,
                       thread=params$thread,
                       exe_veryfasttree=params$exe_veryfasttree)

        # refine the species tree using IQ-TREE2
        f_iqtree2(fn_input=fn_concatenated_filtered,
                  fn_tree=fn_veryfasttree,
                  fn_partition=fn_partition_model,
                  prefix=paste0(outdir_final_treeshrink, "/concat"),
                  thread=params$thread,
                  is_redo=params$redo,
                  exe_iqtree2=params$exe_iqtree)
    }
}

# move all locus trees onto one file
system(paste("cat",
             paste0(outdir_locus_tree, "/*.treefile"),
             ">", fn_alltrees_tre))

# check if file exists
if (!file.exists(fn_astral_tre) || params$redo) {
    # calculate qCF using Astral4
    f_astral4(fn_input=fn_alltrees_tre,
              fn_tree=fn_concat_tre,
              fn_output=fn_astral_tre,
              fn_log=fn_astral_log,
              thread=params$thread,
              exe_astral=params$exe_astral4)
} 

# calculate sCF and gCF
f_calculate_cf(fn_all_trees=fn_alltrees_tre,
               fn_sp_tree=fn_astral_tre,
               dir_fasta=outdir_final_trimlabel,
               prefix=paste0(outdir_final_treeshrink, "/iqtree_concord"),
               thread=params$thread,
               is_redo=params$redo,
               exe_iqtree2=params$exe_iqtree)
```


```{r tree-constrained, eval=params$run_constrained_tree}
# create output directory
outdir_locus_tree_constrained <- file.path(outdir_final_treeshrink, "trees_constrained")
if (!dir.exists(outdir_locus_tree_constrained)) {
    dir.create(outdir_locus_tree_constrained, recursive=T)
}

# open species tree
sptre <- ape::read.tree(fn_concat_tre)
ls_tips <- sptre$tip.label
if (params$fn_species_tree!="" && file.exists(params$fn_species_tree)) {
    previous_sptre <- ape::read.tree(params$fn_species_tree)
    ls_tips <- ls_tips[!ls_tips%in%previous_sptre$tip.label]
}

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# output data.frame
df_iqtree_input <- data.table::data.table()

# iterate over species
for (tips in ls_tips) {
    # output directory and file
    outdir_constrained_tips <- file.path(outdir_locus_tree_constrained, tips)
    
    # subset species tree
    sptre_subset <- ape::drop.tip(sptre, tip=tips)

    # iterate over locus
    df_iqtree_input_tips <- foreach (locus=ls_locus, .combine='rbind') %dopar% {
        # output directory and file
        outdir_constrained_tips_locus <- file.path(outdir_constrained_tips, locus)
        if (!dir.exists(outdir_constrained_tips_locus)) {
            dir.create(outdir_constrained_tips_locus, recursive=T)
        }

        prefix <- paste0(outdir_constrained_tips_locus, "/", locus)
        fn_sptree_subset_locus <- file.path(outdir_constrained_tips_locus, "concat_subset.tre")
        
        # check if tips exists on locus alignment
        fn_input <- file.path(outdir_locus_alignment, paste0(locus, ".fna"))
        seq_subset <- Biostrings::readBStringSet(fn_input)
        if (!tips%in%names(seq_subset)) {
            return(NULL)
        }

        # subset species tree
        sptre_subset_locus <- ape::keep.tip(sptre_subset, tip=sptre_subset$tip.label[sptre_subset$tip.label%in%names(seq_subset)])
        sptre_subset_locus$node.label <- NULL
        sptre_subset_locus$edge.length <- NULL
        ape::write.tree(sptre_subset_locus, file=fn_sptree_subset_locus)

        return(data.table::data.table(fn_input=fn_input,
                                      fn_tree=fn_sptree_subset_locus,
                                      prefix=prefix))
    }

    # update data.frame
    df_iqtree_input <- rbind(df_iqtree_input, df_iqtree_input_tips)
}

# run IQ-TREE2
foreach (i=1:nrow(df_iqtree_input)) %dopar% {
    f_iqtree2_fixtop(fn_input=df_iqtree_input$fn_input[i],
                     fn_tree=df_iqtree_input$fn_tree[i],
                     fn_partition=NULL,
                     prefix=df_iqtree_input$prefix[i],
                     thread=1,
                     is_redo=params$redo,
                     exe_iqtree2=params$exe_iqtree)
}

stopCluster(nwcl)
```
