---
title: "Summarise Tip Position"
---

```{r summary-setup, include=FALSE}
# create output directories
outdir_summary <- file.path(currentdir, "06_summary")
if (!dir.exists(outdir_summary)) {
    dir.create(outdir_summary, recursive=T)
}
```

```{r summary-genetree}
# open species tree
sptre <- ape::read.tree(fn_iqtree_tre)
ls_tips <- sptre$tip.label
if (params$fn_species_tree!="" && file.exists(params$fn_species_tree)) {
    previous_sptre <- ape::read.tree(params$fn_species_tree)
    ls_tips <- ls_tips[!ls_tips%in%previous_sptre$tip.label]
}

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# iterate over species
for (tips in ls_tips) {
    # output directory and file
    outdir_summary_tips <- file.path(outdir_summary, tips)
    
    # subset species tree
    sptre_subset <- ape::drop.tip(sptre, tip=tips)

    # iterate over locus
    foreach (locus=ls_locus) %dopar% {
        # output directory and file
        outdir_summary_tips_locus <- file.path(outdir_summary_tips, locus)
        if (!dir.exists(outdir_summary_tips_locus)) {
            dir.create(outdir_summary_tips_locus, recursive=T)
        }

        prefix <- paste0(outdir_summary_tips_locus, "/", locus)
        fn_sptree_subset_locus <- file.path(outdir_summary_tips_locus, "iqtree_subset.tre")
        
        # check if tips exists on locus alignment
        fn_input <- file.path(outdir_final_trimlabel, paste0(locus, ".fna"))
        seq_subset <- Biostrings::readBStringSet(fn_input)
        if (!tips%in%names(seq_subset)) {
            return(NULL)
        }

        # subset species tree
        sptre_subset_locus <- ape::keep.tip(sptre_subset, tip=sptre_subset$tip.label[sptre_subset$tip.label%in%names(seq_subset)])
        ape::write.tree(sptre_subset_locus, file=fn_sptree_subset_locus)

        # run IQ-TREE2
        f_iqtree2_fixtop(fn_input=fn_input,
                         fn_tree=fn_sptree_subset_locus,
                         fn_partition=NULL,
                         prefix=prefix,
                         thread=1,
                         is_redo=params$redo,
                         exe_iqtree2=params$exe_iqtree)
    }
}

stopCluster(nwcl)
```

```{r summary-treedist}
# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# initiate variable
df_output <- NULL

# open metadata file
df_eucs_metadata <- readxl::read_xlsx(params$fn_eucs_metadata)

# iterate over species
for (tips in ls_tips) {
    # list locus
    outdir_summary_tips <- file.path(outdir_summary, tips)
    ls_locus <- list.dirs(outdir_summary_tips, recursive=F, full.names=F)

    # iterate over locus
    df_tips <- foreach (locus=ls_locus, .combine='rbind') %dopar% {
        # open treefile
        outdir_summary_tips_locus <- file.path(outdir_summary_tips, locus)
        sptre_subset_locus <- ape::read.tree(file.path(outdir_summary_tips_locus, paste0(locus, ".treefile")))

        # create a distance matrix
        dist_matrix <- ape::cophenetic.phylo(sptre_subset_locus)

        # extract distances from the tip
        dist_to_tips <- dist_matrix[tips, ]
        dist_to_tips <- dist_to_tips[names(dist_to_tips) != tips]

        # get the closest tip
        closest_tip <- names(which.min(dist_to_tips))
        closest_dist <- min(dist_to_tips)

        # extract taxonomy
        genus    <- df_eucs_metadata$genus[df_eucs_metadata$file==closest_tip]
        subgenus <- df_eucs_metadata$subgenus[df_eucs_metadata$file==closest_tip]
        section  <- df_eucs_metadata$section[df_eucs_metadata$file==closest_tip]

        return(data.table::data.table(tips=tips,
                                      locus=locus,
                                      n_tips=length(sptre_subset_locus$tip.label),
                                      closest_tip=closest_tip,
                                      closest_dist=closest_dist,
                                      genus=genus,
                                      subgenus=subgenus,
                                      section=section))
    }

    # update data.frame
    df_output <- rbind(df_output, df_tips)
}

stopCluster(nwcl)

# output files
fn_summary <- file.path(outdir_summary, "closest_tips.tsv")
fn_summary_per_section <- file.path(outdir_summary, "closest_tips_per_section.tsv")

# save data.frame
data.table::fwrite(df_output, file=fn_summary, quote=F, sep="\t")

# summary per section
df_output_per_section <- df_output %>%
                            group_by(tips) %>%
                            mutate(n_sum=n()) %>%
                            group_by(tips, section) %>%
                            reframe(n=n(), percent=round(n/n_sum*100,2)) %>%
                            unique() %>%
                            arrange(tips, desc(percent))
data.table::fwrite(df_output_per_section, file=fn_summary_per_section, quote=F, sep="\t")                            
```
