---
title: "Run HybPiper to extract Crisp101 loci"
author: "Jeremias Ivan"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M%p')`"

output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true

params:
  # general
  codedir: "~/EucsPhylogenomics/"
  outdir: "~/simulation"
  thread: 10

  # input directory
  dir_fastq: ""
  fn_hybpiper_metadata: ""
  fn_coverage_metadata: ""

  # variables
  min_coverage: 10

  # executable
  exe_hybpiper: ""
  exe_mafft: ""
  exe_iqtree2: ""
  exe_astral: ""
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/codes/crisp101/functions.R"))

library(Biostrings)
library(data.table)
library(tidyverse)
```

```{r, include=FALSE}
# install.packages("log4r")

# store initial system time
sys_tic <- Sys.time()

# create outdir
currentdir <- paste0(params$outdir, "/")
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- paste0(params$outdir, "/run_crisp101.log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (params$redo || !file.exists(fn_log)) {
  unlink(fn_log)
  write.table(c("EucsPhylogenomics",
                "Developed by Jeremias Ivan"),
              file=fn_log, quote=F, row.names=F, col.names=F)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r init, include=FALSE}
# open metadata
df_hybpiper_metadata <- data.table::fread(params$fn_hybpiper_metadata)
init_n_sample <- nrow(df_hybpiper_metadata)

# exclude samples with <10x coverage (optional)
if (!is.null(params$fn_coverage_metadata) && file.exists(params$fn_coverage_metadata)) {
    df_coverage <- data.table::fread(params$fn_coverage_metadata)
    df_coverage <- df_coverage %>% filter(cov >= as.numeric(params$min_coverage))
    df_hybpiper_metadata <- df_hybpiper_metadata %>% filter(sample %in% df_coverage$file)
}

cat(paste("Initial number of samples:", init_n_sample))
cat(paste("Final number of samples after excluding low-coverage samples:", nrow(df_hybpiper_metadata)))
```

## Run HybPiper
```{r run-hybpiper}
# create output directory
dir_hybpiper_output <- paste0(params$outdir, "/hybpiper_run/")
if (!dir.exists(dir_hybpiper_output)) {
    dir.create(dir_hybpiper_output, recursive=T)
}

# iterate over samples
for (i in 1:nrow(df_hybpiper_metadata)) {
    msg <- f_hybpiper(sample=df_hybpiper_metadata$sample[i],
                      dir_sample=params$dir_fastq,
                      target_file=df_hybpiper_metadata$target_file[i],
                      data_type=df_hybpiper_metadata$data_type[i],
                      thread=params$thread,
                      outdir=dir_hybpiper_output,
                      exe_hybpiper=params$exe_hybpiper)

    log4r::info(fn_logger, msg)
}

cat("HybPiper runs finished!")
```

## Extract DNA sequences from the original study
```{r extract-sequence-ref}
# create output directory
dir_alignment_output <- paste0(params$outdir, "/alignment/")
if (!dir.exists(dir_alignment_output)) {
    dir.create(dir_alignment_output, recursive=T)
}

# iterate over target file
for (file in unique(df_hybpiper_metadata$target_file)) {
    # open the target file
    seq <- Biostrings::readBStringSet(file)
    ls_locus <- sapply(names(seq), function(x) { header <- unlist(strsplit(x, split="-")); header[length(header)] })
    ls_locus <- unique(ls_locus)

    # iterate over locus
    for (locus in ls_locus) {
        # create output directory
        dir_fasta_output <- paste0(dir_alignment_output, locus, "/")
        if (!dir.exists(dir_fasta_output)) {
            dir.create(dir_fasta_output, recursive=T)
        }

        # output file
        fn_fasta <- paste0(dir_fasta_output, locus, ".fna")
        if (file.exists(fn_fasta)) {
            log4r::warn(fn_logger, paste0("File found: FASTA file for ", locus, ". Locus sequences from the target file will be appended."))
        }

        # extract sequences
        seq_locus <- seq[grepl(paste0("-",locus,"$"), names(seq))]
        names(seq_locus) <- gsub(paste0("-",locus), "", names(seq_locus))

        # save sequences
        Biostrings::writeXStringSet(seq_locus, file=fn_fasta, append=T)
    }
}

# extract final set of locus
ls_locus_final <- list.dirs(dir_alignment_output, recursive=F, full.names=F)

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# iterate over each locus sequence
foreach (locus = ls_locus_final) %dopar% {
    # input and output files
    fn_fasta <- paste0(dir_alignment_output, locus, "/", locus, ".fna")
    fn_fasta_aligned <- paste0(dir_alignment_output, locus, "/", locus, "_aligned.fna")
    f_mafft(fn_fasta, fn_fasta_aligned, params$exe_mafft) 
}

stopCluster(nwcl)
```

## Extract DNA sequences from HybPiper
```{r extract-sequence-hybpiper}
# initiate data.frame to store excluded loci
df_excluded_loci <- data.table::data.table(sample=character(), initial=numeric(), putative_paralogs=numeric(), final=numeric())

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# iterate over samples
for (sample in df_hybpiper_metadata$sample) {
    # directories
    dir_hybpiper_output_sample <- paste0(dir_hybpiper_output, sample, "/")

    # extract the list of locus
    ls_locus_sample <- list.dirs(dir_hybpiper_output_sample, recursive=F, full.names=F)
    init_locus_len <- length(ls_locus_sample)

    # remove putative paralogs
    ls_paralogs_sample <- f_check_hybpiper_paralogs(sample, dir_hybpiper_output_sample)
    ls_locus_sample <- ls_locus_sample[!ls_locus_sample%in%ls_paralogs_sample]

    # iterate over loci
    foreach (locus = ls_locus_sample) %dopar% {
        # output file
        fn_out_hybpiper <- paste0(dir_alignment_output, locus, "/", locus, "_hybpiper.fna")

        # input file
        fn_in_hybpiper <- paste0(dir_hybpiper_output_sample, locus, "/", sample, "/sequences/FNA/", locus, ".FNA")
        if (!file.exists(fn_in_hybpiper)) {
            log4r::error(fn_logger, paste0("File not found: ", locus, " for ", sample))
            return(NULL)
        }

        # open sequence
        seq_in_hybpiper <- Biostrings::readBStringSet(fn_in_hybpiper)

        # convert X into gaps
        for (i in 1:length(seq_in_hybpiper)) {
            seq_in_hybpiper[i] <- gsub("N", "-", seq_in_hybpiper[i])
            seq_in_hybpiper[i] <- gsub("X", "-", seq_in_hybpiper[i])
        }

        Biostrings::writeXStringSet(seq_in_hybpiper, file=fn_out_hybpiper, append=T)
    }

    # update data.frame
    df_excluded_loci <- rbind(df_excluded_loci, data.table::data.table(sample=sample,
                                                                       initial=init_locus_len,
                                                                       putative_paralogs=length(ls_paralogs_sample),
                                                                       final=length(ls_locus_sample)))
}

stopCluster(nwcl)

# save data.frame
data.table::fwrite(df_excluded_loci, file=paste0(params$outdir, "/excluded_loci_per_sample.tsv"), quote=F, sep="\t")
```

## Filter locus alignments
```{r filter}
# create output directory
dir_alignment_final <- paste0(params$outdir, "/final/alignment/")
if (!dir.exists(dir_alignment_final)) {
    dir.create(dir_alignment_final, recursive=T)
}

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# iterate over loci
foreach(locus = ls_locus_final) %dopar% {
    # input files
    fn_fasta_aligned <- paste0(dir_alignment_output, locus, "/", locus, "_aligned.fna")
    fn_fasta_hybpiper <- paste0(dir_alignment_output, locus, "/", locus, "_hybpiper.fna")

    # output files
    fn_combined <- paste0(dir_alignment_output, locus, "/", locus, "_combined.fna")
    fn_final <- paste0(dir_alignment_final, locus, "/", locus, "_final.fna")

    if (all(file.exists(fn_fasta_aligned, fn_fasta_hybpiper))) {
        # run MAFFT
        f_mafft_add(fn_fasta_aligned, fn_fasta_hybpiper, fn_combined, params$exe_mafft)

        # delete sequences with >=50% gaps
        f_remove_seq(fn_combined, fn_final, 0.5)
    }
}

stopCluster(nwcl)
```

## Generate locus trees and species tree
```{r tree}
# create output directory
dir_tree_final <- paste0(params$outdir, "/final/tree/")
if (!dir.exists(dir_tree_final)) {
    dir.create(dir_tree_final, recursive=T)
}

# output files
prefix_alltrees <- paste0(dir_tree_final, "alltrees")
prefix_cf <- paste0(dir_tree_final, "concord")

fn_alltrees <- paste0(prefix_alltrees, ".treefile")
fn_astral_tre <- paste0(dir_tree_final, "astral.treefile")
fn_astral_log <- paste0(dir_tree_final, "astral.log")
fn_cf_stat <- paste0(prefix_cf, ".cf.stat")

# infer gene trees
f_iqtree2_multiple(dir_alignment_final, prefix_alltrees, params$thread, params$exe_iqtree2)

# generate ASTRAL tree
f_astral(fn_alltrees, fn_astral_tre, fn_astral_log, "4g", params$exe_astral)

# calculate gCF and sCF
f_calculate_cf(fn_alltrees, fn_astral_tre, dir_alignment_final, prefix_cf, params$thread, params$exe_iqtree2)

# open the CF output file
astral_tre <- ape::read.tree(fn_astral_tre)
df_cf <- read.delim(fn_cf_stat, header = T, comment.char= '#')

# create doSNOW clusters
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# extract branch length, bootstrap, gCF, and sCF
df_output <- foreach (i = 1:nrow(df_cf), .combine='rbind') %dopar% {
    data.table::data.table(id=df_cf$ID[i],
                           gcf=df_cf$gCF[i],
                           scf=df_cf$sCF[i],
                           pp=df_cf$bootstrap[i],
                           edge_len=min(node_to_tip_distances(astral_tre, df_cf$ID[i])$distance))
}

stopCluster(nwcl)

# visualisation
plot <- ggplot(df_output, aes(x=edge_len, y=gCF, colour=pp)) + geom_point() + scale_colour_viridis(direction = -1)
plot <- ggplot(df_output, aes(x=edge_len, y=sCF, colour=pp)) + geom_point() + scale_colour_viridis(direction = -1)
```